- name: "Testing ansible-lint with invalid variable names"
  hosts: 127.0.0.1
  connection: local

- name: Criando Maquinetas
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
  - maquinetas

#- name: atualizando maquinetas
#  hosts: localhost
#  gather_facts: False
#  tasks:
#    - meta: refresh_inventory

#- name: Aguardando maquinetas subirem para installar K8S
#  hosts: cluster
#  user: ubuntu
#  gather_facts: False
#  tasks:
#    - wait_for_connection:
#        timeout: 300