apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-client
  namespace: graylog
  labels:
    component: elasticsearch
    role: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-client
        # replace image with your own elasticsearch image or a public one
        image: us.gcr.io/elastic-cluster-191900/elasticsearch-danngo:5.6.8
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # These variables are used in the elasticsearch.yml file
        - name: CLUSTER_NAME
          value: graylog
        - name: MEMORY_LOCK
          value: "false"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "true"
        - name: MAX_LOCAL_STORAGE_NODES
          value: "1"
        - name: PROCESSORS
          value: "1"
        - name: HTTP_ENABLE
          value: "true"
        - name: HTTP_CORS_ENABLE
          value: "true"
        - name: HTTP_CORS_ALLOW_ORIGIN
          value: "*"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: ES_PLUGINS_INSTALL
          value: "repository-gcs"
        - name: ES_JAVA_OPTS
          value: -Xms2g -Xmx2g
        - name: NUMBER_OF_MASTERS
          value: "1"
        - name: NETWORK_HOST
          value: _site_,_lo_
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: storage
