apiVersion: v1
kind: Service
metadata:
  labels:
    component: graylog
    role: master
  name: graylog
  namespace: graylog
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: apiport
    port: 12900
    protocol: TCP
    targetPort: 12900
  - name: tcpin
    port: 12300
    targetPort: 12300
    protocol: TCP
  - name: tcpin1
    port: 12301
    targetPort: 12301
    protocol: TCP
  - name: tcpin2
    port: 12302
    targetPort: 12302
    protocol: TCP
  - name: tcpin3
    port: 12303
    targetPort: 12303
    protocol: TCP
  selector:
    component: graylog
    role: master
  sessionAffinity: None
  type: LoadBalancer
