apiVersion: v1
kind: Service
metadata:
  labels:
    component: graylog
    role: graylog-node
  name: graylog-node
  namespace: graylog
spec:
  ports:
  - name: udpin
    port: 12300
    targetPort: 12300
    protocol: UDP
  - name: udpin1
    port: 12301
    targetPort: 12301
    protocol: UDP
  - name: udpin2
    port: 12302
    targetPort: 12302
    protocol: UDP
  - name: udpin3
    port: 12303
    targetPort: 12303
    protocol: UDP
  - name: udpin4
    port: 12304
    targetPort: 12304
    protocol: UDP
  selector:
    component: graylog
    role: graylog-node
  sessionAffinity: None
  type: LoadBalancer
