apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: graylog-ingress 
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /graylog
          backend:
            serviceName: flippant-lion-graylog-web
            servicePort: 9000
