apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-cats-03
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes: 
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-046fa7f2fbdc59c3e
    fsType: ext4
